// frontend/app/test/rice-purity/questions.ts

export const ricePurityQuestions: string[] = [
    // Step 1: Digital Sins & Brainrot
    "Used ChatGPT to write an entire essay or assignment?",
    "Doomscrolled on TikTok/Reels for more than 4 hours straight?",
    "Stalked someone’s location on Snap Map or Find My Friends?",
    "Created a fake account (Finsta/Burner) to spy on someone?",
    "Screenshotted a private conversation and sent it to a group chat?",
    "Left a hate comment on a celebrity or influencer’s post?",
    "Got into a Twitter (X) argument that lasted over an hour?",
    "Paid for a verification badge (Twitter Blue/Meta Verified)?",
    "Filmed a TikTok dance in a crowded public place?",

    // Step 2: Modern Romance & Situationships
    "Been on a date?",
    "Been in a relationship?",
    "Had a 'situationship' that lasted longer than an actual relationship?",
    "Been ghosted by someone you were talking to for months?",
    "Ghosted someone after a first date?",
    "Sent a risky text and unsend it before they read it?",
    "Soft-launched a partner on Instagram stories?",
    "Matched with a friend’s ex on a dating app (Tinder/Hinge)?",
    "Blocked someone just to have the 'last word'?",
    "Gaslit someone into thinking they were crazy?",

    // Classic Physical Intimacy (Retained)
    "Kissed a non-family member?",
    "French kissed?",
    "Given or received a hickey?",
    "Kissed someone below the belt?",
    "Seen or been seen by another person in a sensual context?",
    "Masturbated?",
    "Masturbated to a picture or video?",
    "Masturbated while someone else was in the room?",
    "Been caught masturbating?",

    // Step 4: Digital Wild Side
    "Received a nude photo via AirDrop from a stranger?",
    "Sent a nude photo (Solicited or Unsolicited)?",
    "Sent a sexually explicit text or instant message?",
    "Engaged in sexually explicit activity over video chat?",
    "Subscribed to an OnlyFans?",
    "Sold content on OnlyFans or Fansly?",

    // Step 3: Vices 2.0 & Partying
    "Been drunk?",
    "Blacked out and checked phone the next morning in horror?",
    "Played a drinking game?",
    "Used marijuana?",
    "Own or have owned a vape (Elf Bar, Juul, etc.)?",
    "Hit a vape in a school bathroom or workplace restroom?",
    "Been addicted to Zyn or nicotine pouches?",
    "Taken Adderall or Xanax without a prescription?",
    "Used a drug stronger than marijuana?",
    "Sold drugs?",

    // Step 5: Random Chaos & Mischief
    "Shopifted something worth less than $10?",
    "Lied about your age to get into a club or bar?",
    "Faked a location to get out of a plan?",
    "Lost money on a Crypto or NFT scam?",
    "Gone skinny-dipping?",
    "Gone streaking?",
    "Been arrested?",
    "Been convicted of a crime?",

    // Sexual Experience (Classic + Updated)
    "Had sexual intercourse?",
    "Had oral sex?",
    "Gave oral sex?",
    "Received oral sex?",
    "Had sexual intercourse in a motor vehicle?",
    "Had sexual intercourse outdoors?",
    "Had sexual intercourse while someone else was in the room (sleeping or awake)?",
    "Hooked up with someone you met on the internet within 24 hours?",
    "Participated in a 'booty call'?",
    "Had sexual intercourse with a partner with a 3 or more year age difference?",
    "Had sexual intercourse without a condom?",
    "Had a STI test due to a reasonable suspicion?",
    "Had a STI?",
    "Had a pregnancy scare?",
    "Impregnated someone or been impregnated?",
    "Paid or been paid for a sexual act?",
    "Had sexual intercourse with 5 or more partners?",
    "Had sexual intercourse with 10 or more partners?",
    "Had sexual intercourse with 20 or more partners?",
    "Been photographed or filmed during sexual intercourse?",
    "Had anal sex?",
    "Had a threesome?",
    "Attended an orgy?",

    // Deep Cut Classics (Fillers for 100)
    "Shower with a MPS (Member of Preferred Sex)?",
    "Used a sex toy with a partner?",
    "Spent the night with a MPS?",
    "Been walked in on while engaging in a sexual act?",
    "Kicked a roommate out to commit a sexual act?",
    "Ingested alcohol in a non-religious context?",
    "Faked sobriety to parents or teachers?",
    "Urinated in public?",
    "Seen a stripper?",
    "Had the police question you?",
    "Had sexual intercourse 3 or more times in one night?",
    "Had sexual intercourse in 4 or more different positions?",
    "Had sexual intercourse in a swimming pool or hot tub?",
    "Joined the mile high club?",
    "Traveled 100 or more miles for the primary purpose of sexual intercourse?",
    "Had sexual intercourse with a virgin?",
    "Committed an act of voyeurism?",
    "Had period sex?",
    "Had 2 or more distinct acts of sexual intercourse with 2 or more people within 24 hours?",
    "Committed an act of vandalism?",
    "Run from the police?",
    "Committed an act of incest?",
    "Engaged in bestiality?"
];
